### PR TITLE
Adds linter rule to prevent raw text in jsx text elements

### PR DESCRIPTION
**Pull request by Omniwheel**
Blocks: https://github.com/Root-App/root-mobile/pull/6129

### CODE REVIEW

**Review by mjgerace — APPROVED** [review]

**Comment by Omniwheel** [comment]
[ch14749]

**Comment by qwoodmansee** [comment]
I would definitely **not** like this merged until we have solid documentation (e.g. step by step) on how to use the new local system

**Comment by Omniwheel** [comment]
> I would definitely **not** like this merged until we have solid documentation (e.g. step by step) on how to use the new local system

Yea, we are working on it. I won't merge the `root-mobile` change until we have documentation.

**Review by scottkeller — APPROVED** [review]
⚔️

**Review by mjgerace — APPROVED** [review]

**Pull request merged**
