### PR TITLE
Prevent use of window.location linter rule

### PR DESCRIPTION
**Pull request by patveith**

### CODE REVIEW

**Comment by patveith** [comment]
[Linter: prevent usage of window.location](https://trello.com/c/5Jpk3wfJ/321-linter-prevent-usage-of-windowlocation)

**Comment by TAGraves** [comment]
I think we want to go a little more broad with this. We don't want to just prevent assignment - we want to prevent reading it altogether. I.e., this code should fail:

```
function A() {
  if (window.location.href === 'blah') {
    ...
  }
}
```

**Comment by patveith** [comment]
@TAGraves Updated to fail on member expression containing window.location.

**Comment by patveith** [comment]
```
patrick@Patricks-MacBook-Pro:~/code/root-web [pv-which-driver|✚ 3] $ yarn lint
yarn run v1.9.2
$ eslint modules
Warning: React version not specified in eslint-plugin-react settings. See https://github.com/yannickcr/eslint-plugin-react#configuration.

/Users/patrick/code/root-web/modules/landing/src/scenes/landing-reset-confirm.js
  15:24  error  Use props.location instead by wrapping component with a router  root/prevent-use-of-window-location

✖ 1 problem (1 error, 0 warnings)

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by tylerkucera** [comment]
[Add a linter rule preventing relative paths.](https://trello.com/c/NQ6eFZf1/357-add-a-linter-rule-preventing-relative-paths)

**Pull request merged**
